### ISSUE TITLE
Status indicator

### ISSUE THREAD

**Issue by hoeg** [epadctf/PadDown#2]
Status of the running decryption

**Comment by RobatBender** [comment]
can be more detailed

**Comment by hoeg** [comment]
it could be something as simple as an indicator on the screen than shows how much of the ciphertext have been decrypted.

Would like it to be an option that you can set on the decrypt engine if you want this printed out or not.

**Comment by theilgaard** [comment]
We could progressively show the intermediate key being found, but I honestly I think this would look very ugly once we pass a certain size of ciphertext.

Perhaps a simple percentage would be nice?

**Comment by theilgaard** [comment]
Closed in pr #30
