### ISSUE TITLE
Project set up

### ISSUE THREAD

**Issue by MarvinKweyu** [epadctf/PadDown#29]
So I seem to have found a solution to one of the issues, but I am having trouble committing the changes. Specifically the [.pre-commit-config.yaml](https://github.com/epadctf/Paddown/blob/master/.pre-commit-config.yaml). Can this be set to use a version of `python >=3.7` ?

**Comment by theilgaard** [comment]
Which issue/solution are you referring to? Feel free to change it to `python >=3.7` and submit a pull request.

**Comment by theilgaard** [comment]
Closed by pr #30
