### ISSUE TITLE
CI!

### ISSUE THREAD

**Issue by hoeg** [epadctf/PadDown#5]
Of course we should have some kind of CI

**Comment by RobatBender** [comment]
How about CircleCI?

**Comment by hoeg** [comment]
Circle is fine. I do suspect that we will need some tests, a way to publish to pip and have the repo ready as a package before it makes sense to set this up.

Did you have anything else in mind for CI?

**Comment by RobatBender** [comment]
Can u write tests?
Or i can run linter in CI

**Comment by theilgaard** [comment]
Linter is a good start :) We can always add tests when they have been written.
