### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by theilgaard** [epadctf/PadDown#6]

**Comment by CianWoods1992** [comment]
I can do this

**Comment by hoeg** [comment]
go right ahead :)

**Comment by CianWoods1992** [comment]
@hoeg I don't seem to have permission to push a branch to remote?

**Comment by theilgaard** [comment]
You must fork the repo, push the change to your own repo, and then submit a pull request.

**Comment by theilgaard** [comment]
Closing this for being too generic.
